spring:
  # MySQL数据库连接信息
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://58.206.100.88:3306/community
    username: root
    password: stu2023

  # Redis配置
  redis:
    database: 0
    host: 58.206.100.88
    port: 6379
    password: stu2023

  # Elasticsearch配置
  data:
    elasticsearch:
      cluster-nodes: 58.206.100.88:9300
      cluster-name: bigc
  elasticsearch:
    rest:
      uris:
        - http://58.206.100.88:9200

  # Kafka配置
  kafka:
    bootstrap-servers: 58.206.100.88:9092
    consumer:
      group-id: community-consumer-group
      enable-auto-commit: true
      auto-commit-interval: 3000


  # 关闭Thymeleaf的缓存
  thymeleaf:
    cache:
      false

  # Mail配置
  mail:
    host: smtp.qq.com
    port: 465
    username: 1339852932@qq.com
    password: wimratzxzflihejc
    protocol: smtps
    properties:
      mail:
        smtp:
          ssl:
            enable: true
    default-encoding: UTF-8

  # Quartz配置
  quartz:
    job-store-type: jdbc
    scheduler-name: communityScheduler
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            isClustered: true
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 5


mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    use-generated-keys: true

# 路径
server:
  servlet:
    context-path: /community

# community
community:
  path:
    domain: http://localhost:8080
    upload: /Users/qianlong/Git/Study/project/work/niuke-project/community/src/main/resources/upload

# caffeine
caffeine:
  posts:
    max-size: 15
    expire-seconds: 180
